const allDelivery = [
  {
    id: "#D1001",
    consignee: "Connaught Place",
    location: "Delhi",
    status: "In Transit",
    vehicle: "DL 1LA 1234",
    driver: "Rohit Sharma",
    eta: "2:30 PM",
    action: ":",
  },
  {
    id: "#D1002",
    consignee: "India Gate",
    location: "Delhi",
    status: "Delivered",
    vehicle: "DL 3CB 4521",
    driver: "Amit Kumar",
    eta: "11:45 AM",
    action: ":",
  },
  {
    id: "#D1003",
    consignee: "Cyber City",
    location: "Gurgaon",
    status: "Pending",
    vehicle: "HR 26 DK 8890",
    driver: "Suresh Yadav",
    eta: "4:15 PM",
    action: ":",
  },
  {
    id: "#D1004",
    consignee: "Sector 18",
    location: "Noida",
    status: "In Transit",
    vehicle: "UP 16 AB 3421",
    driver: "Vikas Singh",
    eta: "3:00 PM",
    action: ":",
  },
  {
    id: "#D1005",
    consignee: "MG Road",
    location: "Gurgaon",
    status: "Delivered",
    vehicle: "HR 55 AC 9087",
    driver: "Rahul Verma",
    eta: "10:20 AM",
    action: ":",
  },
  {
    id: "#D1006",
    consignee: "Karol Bagh",
    location: "Delhi",
    status: "Delayed",
    vehicle: "DL 8C AT 5512",
    driver: "Manoj Kumar",
    eta: "5:30 PM",
    action: ":",
  },
  {
    id: "#D1007",
    consignee: "Andheri",
    location: "Mumbai",
    status: "In Transit",
    vehicle: "MH 01 AB 7788",
    driver: "Rakesh Patel",
    eta: "6:00 PM",
    action: ":",
  },
  {
    id: "#D1008",
    consignee: "Bandra",
    location: "Mumbai",
    status: "Delivered",
    vehicle: "MH 02 XY 4432",
    driver: "Deepak Singh",
    eta: "12:10 PM",
    action: ":",
  },
  {
    id: "#D1009",
    consignee: "Powai",
    location: "Mumbai",
    status: "Pending",
    vehicle: "MH 03 CD 9912",
    driver: "Arjun Mehta",
    eta: "7:00 PM",
    action: ":",
  },
  {
    id: "#D1010",
    consignee: "Salt Lake",
    location: "Kolkata",
    status: "In Transit",
    vehicle: "WB 02 AA 5544",
    driver: "Ankit Roy",
    eta: "3:45 PM",
    action: ":",
  },

  {
    id: "#D1011",
    consignee: "Park Street",
    location: "Kolkata",
    status: "Delivered",
    vehicle: "WB 06 BB 2211",
    driver: "Sanjay Das",
    eta: "1:30 PM",
    action: ":",
  },
  {
    id: "#D1012",
    consignee: "Ballygunge",
    location: "Kolkata",
    status: "Delayed",
    vehicle: "WB 20 CC 7766",
    driver: "Rajesh Gupta",
    eta: "8:00 PM",
    action: ":",
  },
  {
    id: "#D1013",
    consignee: "Banjara Hills",
    location: "Hyderabad",
    status: "In Transit",
    vehicle: "TS 09 AA 3322",
    driver: "Karan Reddy",
    eta: "4:40 PM",
    action: ":",
  },
  {
    id: "#D1014",
    consignee: "Hitech City",
    location: "Hyderabad",
    status: "Pending",
    vehicle: "TS 10 AB 7789",
    driver: "Naveen Kumar",
    eta: "6:15 PM",
    action: ":",
  },
  {
    id: "#D1015",
    consignee: "Jubilee Hills",
    location: "Hyderabad",
    status: "Delivered",
    vehicle: "TS 11 AC 4433",
    driver: "Praveen Reddy",
    eta: "9:50 AM",
    action: ":",
  },
  {
    id: "#D1016",
    consignee: "Koramangala",
    location: "Bangalore",
    status: "In Transit",
    vehicle: "KA 01 AB 2233",
    driver: "Vijay Kumar",
    eta: "5:10 PM",
    action: ":",
  },
  {
    id: "#D1017",
    consignee: "Whitefield",
    location: "Bangalore",
    status: "Delivered",
    vehicle: "KA 03 CD 8899",
    driver: "Ajay Singh",
    eta: "2:00 PM",
    action: ":",
  },
  {
    id: "#D1018",
    consignee: "Indiranagar",
    location: "Bangalore",
    status: "Pending",
    vehicle: "KA 05 EF 6655",
    driver: "Sunil Kumar",
    eta: "7:30 PM",
    action: ":",
  },
  {
    id: "#D1019",
    consignee: "T Nagar",
    location: "Chennai",
    status: "In Transit",
    vehicle: "TN 01 AA 9090",
    driver: "Dinesh Kumar",
    eta: "4:20 PM",
    action: ":",
  },
  {
    id: "#D1020",
    consignee: "Velachery",
    location: "Chennai",
    status: "Delayed",
    vehicle: "TN 07 BB 5566",
    driver: "Mohan Raj",
    eta: "8:30 PM",
    action: ":",
  },

  {
    id: "#D1021",
    consignee: "Adyar",
    location: "Chennai",
    status: "Delivered",
    vehicle: "TN 10 CC 1122",
    driver: "Arun Kumar",
    eta: "11:00 AM",
    action: ":",
  },
  {
    id: "#D1022",
    consignee: "Civil Lines",
    location: "Jaipur",
    status: "In Transit",
    vehicle: "RJ 14 AB 3421",
    driver: "Mahesh Sharma",
    eta: "3:30 PM",
    action: ":",
  },
  {
    id: "#D1023",
    consignee: "Malviya Nagar",
    location: "Jaipur",
    status: "Pending",
    vehicle: "RJ 27 CD 8890",
    driver: "Pankaj Jain",
    eta: "6:45 PM",
    action: ":",
  },
  {
    id: "#D1024",
    consignee: "Vaishali Nagar",
    location: "Jaipur",
    status: "Delivered",
    vehicle: "RJ 45 EF 5566",
    driver: "Lokesh Gupta",
    eta: "12:30 PM",
    action: ":",
  },
  {
    id: "#D1025",
    consignee: "Hazratganj",
    location: "Lucknow",
    status: "Delayed",
    vehicle: "UP 32 AA 1122",
    driver: "Imran Khan",
    eta: "5:00 PM",
    action: ":",
  },
  {
    id: "#D1026",
    consignee: "Gomti Nagar",
    location: "Lucknow",
    status: "Delayed",
    vehicle: "UP 32 BB 3344",
    driver: "Faizan Ali",
    eta: "8:15 PM",
    action: ":",
  },
  {
    id: "#D1027",
    consignee: "Aliganj",
    location: "Lucknow",
    status: "Delivered",
    vehicle: "UP 32 CC 7788",
    driver: "Nitin Singh",
    eta: "1:15 PM",
    action: ":",
  },
  {
    id: "#D1028",
    consignee: "Koregaon Park",
    location: "Pune",
    status: "In Transit",
    vehicle: "MH 12 AB 3456",
    driver: "Sachin Patil",
    eta: "4:00 PM",
    action: ":",
  },
  {
    id: "#D1029",
    consignee: "Hinjewadi",
    location: "Pune",
    status: "Pending",
    vehicle: "MH 14 XY 9988",
    driver: "Ganesh Jadhav",
    eta: "7:45 PM",
    action: ":",
  },
  {
    id: "#D1030",
    consignee: "Viman Nagar",
    location: "Pune",
    status: "Delivered",
    vehicle: "MH 12 CD 2233",
    driver: "Ravi Shinde",
    eta: "10:40 AM",
    action: ":",
  },

  {
    id: "#D1031",
    consignee: "SG Highway",
    location: "Ahmedabad",
    status: "Delayed",
    vehicle: "GJ 01 AB 7788",
    driver: "Harsh Patel",
    eta: "3:20 PM",
    action: ":",
  },
  {
    id: "#D1032",
    consignee: "Navrangpura",
    location: "Ahmedabad",
    status: "Delivered",
    vehicle: "GJ 05 CD 5544",
    driver: "Jay Patel",
    eta: "12:00 PM",
    action: ":",
  },
  {
    id: "#D1033",
    consignee: "Maninagar",
    location: "Ahmedabad",
    status: "Delayed",
    vehicle: "GJ 27 EF 9988",
    driver: "Meet Shah",
    eta: "6:30 PM",
    action: ":",
  },
  {
    id: "#D1034",
    consignee: "MP Nagar",
    location: "Bhopal",
    status: "In Transit",
    vehicle: "MP 04 AA 4455",
    driver: "Aakash Verma",
    eta: "4:50 PM",
    action: ":",
  },
  {
    id: "#D1035",
    consignee: "Arera Colony",
    location: "Bhopal",
    status: "Delayed",
    vehicle: "MP 04 BB 6677",
    driver: "Ramesh Yadav",
    eta: "9:00 PM",
    action: ":",
  },
  {
    id: "#D1036",
    consignee: "Vijay Nagar",
    location: "Indore",
    status: "Delivered",
    vehicle: "MP 09 AB 2233",
    driver: "Sandeep Sharma",
    eta: "11:20 AM",
    action: ":",
  },
  {
    id: "#D1037",
    consignee: "Palasia",
    location: "Indore",
    status: "In Transit",
    vehicle: "MP 09 CD 7788",
    driver: "Ashish Gupta",
    eta: "5:40 PM",
    action: ":",
  },
  {
    id: "#D1038",
    consignee: "Kankarbagh",
    location: "Patna",
    status: "Pending",
    vehicle: "BR 01 AA 3344",
    driver: "Ravi Kumar",
    eta: "7:10 PM",
    action: ":",
  },
  {
    id: "#D1039",
    consignee: "Boring Road",
    location: "Patna",
    status: "Delayed",
    vehicle: "BR 01 BB 5566",
    driver: "Mukesh Kumar",
    eta: "3:15 PM",
    action: ":",
  },
  {
    id: "#D1040",
    consignee: "Fraser Road",
    location: "Patna",
    status: "Delivered",
    vehicle: "BR 01 CC 8899",
    driver: "Pawan Singh",
    eta: "1:00 PM",
    action: ":",
  },

  {
    id: "#D1041",
    consignee: "Sector 17",
    location: "Chandigarh",
    status: "In Transit",
    vehicle: "CH 01 AB 1111",
    driver: "Gurpreet Singh",
    eta: "4:30 PM",
    action: ":",
  },
  {
    id: "#D1042",
    consignee: "Sector 22",
    location: "Chandigarh",
    status: "Delivered",
    vehicle: "CH 01 CD 2222",
    driver: "Harpreet Singh",
    eta: "10:30 AM",
    action: ":",
  },
  {
    id: "#D1043",
    consignee: "Sector 35",
    location: "Chandigarh",
    status: "Delayed",
    vehicle: "CH 01 EF 3333",
    driver: "Jaspreet Singh",
    eta: "6:20 PM",
    action: ":",
  },
  {
    id: "#D1044",
    consignee: "Mall Road",
    location: "Shimla",
    status: "Delayed",
    vehicle: "HP 01 AA 4455",
    driver: "Rohit Thakur",
    eta: "8:45 PM",
    action: ":",
  },
  {
    id: "#D1045",
    consignee: "Lakkar Bazar",
    location: "Shimla",
    status: "In Transit",
    vehicle: "HP 02 BB 6677",
    driver: "Aman Verma",
    eta: "5:15 PM",
    action: ":",
  },
  {
    id: "#D1046",
    consignee: "Gomti Nagar",
    location: "Lucknow",
    status: "Delivered",
    vehicle: "UP 32 DD 4455",
    driver: "Shivam Mishra",
    eta: "12:45 PM",
    action: ":",
  },
  {
    id: "#D1047",
    consignee: "Rajendra Nagar",
    location: "Delhi",
    status: "In Transit",
    vehicle: "DL 04 AA 5566",
    driver: "Abhishek Kumar",
    eta: "3:50 PM",
    action: ":",
  },
  {
    id: "#D1048",
    consignee: "Dwarka",
    location: "Delhi",
    status: "Pending",
    vehicle: "DL 09 BB 7788",
    driver: "Sumit Sharma",
    eta: "7:30 PM",
    action: ":",
  },
  {
    id: "#D1049",
    consignee: "Rohini",
    location: "Delhi",
    status: "Delivered",
    vehicle: "DL 10 CC 9900",
    driver: "Vivek Kumar",
    eta: "2:10 PM",
    action: ":",
  },
  {
    id: "#D1050",
    consignee: "Lajpat Nagar",
    location: "Delhi",
    status: "Delayed",
    vehicle: "DL 07 DD 1122",
    driver: "Kapil Verma",
    eta: "8:10 PM",
    action: ":",
  },

  {
    id: "#D1051",
    consignee: "Wakad",
    location: "Pune",
    status: "In Transit",
    vehicle: "MH 14 AA 1234",
    driver: "Nilesh Patil",
    eta: "4:25 PM",
    action: ":",
  },
  {
    id: "#D1052",
    consignee: "Kothrud",
    location: "Pune",
    status: "Delivered",
    vehicle: "MH 12 BB 5678",
    driver: "Pratik Jadhav",
    eta: "11:35 AM",
    action: ":",
  },
  {
    id: "#D1053",
    consignee: "Baner",
    location: "Pune",
    status: "Pending",
    vehicle: "MH 12 CC 9876",
    driver: "Akash Pawar",
    eta: "6:55 PM",
    action: ":",
  },
  {
    id: "#D1054",
    consignee: "Borivali",
    location: "Mumbai",
    status: "In Transit",
    vehicle: "MH 47 AB 2233",
    driver: "Sameer Khan",
    eta: "5:30 PM",
    action: ":",
  },
  {
    id: "#D1055",
    consignee: "Dadar",
    location: "Mumbai",
    status: "Delivered",
    vehicle: "MH 01 CD 4455",
    driver: "Salman Shaikh",
    eta: "1:40 PM",
    action: ":",
  },
  {
    id: "#D1056",
    consignee: "Kurla",
    location: "Mumbai",
    status: "Delayed",
    vehicle: "MH 03 EF 6677",
    driver: "Irfan Khan",
    eta: "9:15 PM",
    action: ":",
  },
  {
    id: "#D1057",
    consignee: "Saket",
    location: "Delhi",
    status: "In Transit",
    vehicle: "DL 12 AA 7788",
    driver: "Anil Sharma",
    eta: "4:35 PM",
    action: ":",
  },
  {
    id: "#D1058",
    consignee: "Greater Kailash",
    location: "Delhi",
    status: "Delivered",
    vehicle: "DL 13 BB 9900",
    driver: "Nikhil Gupta",
    eta: "12:20 PM",
    action: ":",
  },
  {
    id: "#D1059",
    consignee: "Vasant Kunj",
    location: "Delhi",
    status: "Pending",
    vehicle: "DL 14 CC 1133",
    driver: "Tushar Singh",
    eta: "7:25 PM",
    action: ":",
  },
  {
    id: "#D1060",
    consignee: "Janakpuri",
    location: "Delhi",
    status: "In Transit",
    vehicle: "DL 15 DD 2244",
    driver: "Hemant Kumar",
    eta: "5:45 PM",
    action: ":",
  },

  {
    id: "#D1061",
    consignee: "Ashok Nagar",
    location: "Ranchi",
    status: "Delivered",
    vehicle: "JH 01 AA 1234",
    driver: "Ranjit Kumar",
    eta: "10:15 AM",
    action: ":",
  },
  {
    id: "#D1062",
    consignee: "Doranda",
    location: "Ranchi",
    status: "In Transit",
    vehicle: "JH 01 BB 2345",
    driver: "Manish Kumar",
    eta: "4:10 PM",
    action: ":",
  },
  {
    id: "#D1063",
    consignee: "Lalpur",
    location: "Ranchi",
    status: "Pending",
    vehicle: "JH 01 CC 3456",
    driver: "Vijay Prasad",
    eta: "7:20 PM",
    action: ":",
  },
  {
    id: "#D1064",
    consignee: "Kankarbagh",
    location: "Patna",
    status: "Delayed",
    vehicle: "BR 02 DD 4567",
    driver: "Neeraj Kumar",
    eta: "8:50 PM",
    action: ":",
  },
  {
    id: "#D1065",
    consignee: "Rajendra Nagar",
    location: "Patna",
    status: "Delivered",
    vehicle: "BR 01 EE 5678",
    driver: "Santosh Kumar",
    eta: "1:25 PM",
    action: ":",
  },
  {
    id: "#D1066",
    consignee: "Civil Lines",
    location: "Allahabad",
    status: "In Transit",
    vehicle: "UP 70 AA 6789",
    driver: "Ajit Singh",
    eta: "3:55 PM",
    action: ":",
  },
  {
    id: "#D1067",
    consignee: "Naini",
    location: "Allahabad",
    status: "Pending",
    vehicle: "UP 70 BB 7890",
    driver: "Rajat Mishra",
    eta: "6:40 PM",
    action: ":",
  },
  {
    id: "#D1068",
    consignee: "Kalyani Nagar",
    location: "Pune",
    status: "Delivered",
    vehicle: "MH 12 FF 8901",
    driver: "Swapnil Patil",
    eta: "11:50 AM",
    action: ":",
  },
  {
    id: "#D1069",
    consignee: "Pimpri",
    location: "Pune",
    status: "In Transit",
    vehicle: "MH 14 GG 9012",
    driver: "Amol Shinde",
    eta: "5:05 PM",
    action: ":",
  },
  {
    id: "#D1070",
    consignee: "Aundh",
    location: "Pune",
    status: "Delayed",
    vehicle: "MH 12 HH 1123",
    driver: "Kunal Jadhav",
    eta: "8:35 PM",
    action: ":",
  },

  {
    id: "#D1071",
    consignee: "Sector 62",
    location: "Noida",
    status: "In Transit",
    vehicle: "UP 16 AA 2234",
    driver: "Varun Kumar",
    eta: "4:20 PM",
    action: ":",
  },
  {
    id: "#D1072",
    consignee: "Sector 18",
    location: "Noida",
    status: "Delivered",
    vehicle: "UP 16 BB 3345",
    driver: "Tarun Singh",
    eta: "12:05 PM",
    action: ":",
  },
  {
    id: "#D1073",
    consignee: "Sector 76",
    location: "Noida",
    status: "Pending",
    vehicle: "UP 16 CC 4456",
    driver: "Mohit Verma",
    eta: "7:35 PM",
    action: ":",
  },
  {
    id: "#D1074",
    consignee: "Udyog Vihar",
    location: "Gurgaon",
    status: "In Transit",
    vehicle: "HR 26 AA 5567",
    driver: "Dev Kumar",
    eta: "5:15 PM",
    action: ":",
  },
  {
    id: "#D1075",
    consignee: "Sector 29",
    location: "Gurgaon",
    status: "Delivered",
    vehicle: "HR 26 BB 6678",
    driver: "Naveen Singh",
    eta: "1:10 PM",
    action: ":",
  },
  {
    id: "#D1076",
    consignee: "Sector 56",
    location: "Gurgaon",
    status: "Delayed",
    vehicle: "HR 26 CC 7789",
    driver: "Yogesh Kumar",
    eta: "9:05 PM",
    action: ":",
  },
  {
    id: "#D1077",
    consignee: "Rajpur Road",
    location: "Dehradun",
    status: "In Transit",
    vehicle: "UK 07 AA 8890",
    driver: "Prakash Rawat",
    eta: "4:45 PM",
    action: ":",
  },
  {
    id: "#D1078",
    consignee: "Clock Tower",
    location: "Dehradun",
    status: "Pending",
    vehicle: "UK 07 BB 9901",
    driver: "Arvind Negi",
    eta: "7:50 PM",
    action: ":",
  },
  {
    id: "#D1079",
    consignee: "Prem Nagar",
    location: "Dehradun",
    status: "Delivered",
    vehicle: "UK 07 CC 1012",
    driver: "Vikas Rawat",
    eta: "11:15 AM",
    action: ":",
  },
  {
    id: "#D1080",
    consignee: "Mall Road",
    location: "Kanpur",
    status: "In Transit",
    vehicle: "UP 78 AA 2123",
    driver: "Amit Tiwari",
    eta: "3:40 PM",
    action: ":",
  },

  {
    id: "#D1081",
    consignee: "Swaroop Nagar",
    location: "Kanpur",
    status: "Delivered",
    vehicle: "UP 78 BB 3234",
    driver: "Rohit Mishra",
    eta: "12:35 PM",
    action: ":",
  },
  {
    id: "#D1082",
    consignee: "Kalyanpur",
    location: "Kanpur",
    status: "Pending",
    vehicle: "UP 78 CC 4345",
    driver: "Gaurav Singh",
    eta: "6:50 PM",
    action: ":",
  },
  {
    id: "#D1083",
    consignee: "Gomti Nagar Extension",
    location: "Lucknow",
    status: "In Transit",
    vehicle: "UP 32 EE 5456",
    driver: "Rakesh Mishra",
    eta: "5:20 PM",
    action: ":",
  },
  {
    id: "#D1084",
    consignee: "Charbagh",
    location: "Lucknow",
    status: "Delayed",
    vehicle: "UP 32 FF 6567",
    driver: "Aman Srivastava",
    eta: "8:55 PM",
    action: ":",
  },
  {
    id: "#D1085",
    consignee: "Alambagh",
    location: "Lucknow",
    status: "Delivered",
    vehicle: "UP 32 GG 7678",
    driver: "Vikas Tripathi",
    eta: "10:55 AM",
    action: ":",
  },
  {
    id: "#D1086",
    consignee: "Alkapuri",
    location: "Vadodara",
    status: "In Transit",
    vehicle: "GJ 06 AA 8789",
    driver: "Bhavesh Patel",
    eta: "4:30 PM",
    action: ":",
  },
  {
    id: "#D1087",
    consignee: "Gotri",
    location: "Vadodara",
    status: "Pending",
    vehicle: "GJ 06 BB 9890",
    driver: "Kishan Patel",
    eta: "7:15 PM",
    action: ":",
  },
  {
    id: "#D1088",
    consignee: "Sayajigunj",
    location: "Vadodara",
    status: "Delivered",
    vehicle: "GJ 06 CC 1098",
    driver: "Hardik Shah",
    eta: "1:30 PM",
    action: ":",
  },
  {
    id: "#D1089",
    consignee: "R City Mall",
    location: "Mumbai",
    status: "In Transit",
    vehicle: "MH 04 AA 2201",
    driver: "Nikhil Patil",
    eta: "5:50 PM",
    action: ":",
  },
  {
    id: "#D1090",
    consignee: "Lower Parel",
    location: "Mumbai",
    status: "Delivered",
    vehicle: "MH 01 BB 3302",
    driver: "Vishal More",
    eta: "12:50 PM",
    action: ":",
  },

  {
    id: "#D1091",
    consignee: "Colaba",
    location: "Mumbai",
    status: "Pending",
    vehicle: "MH 01 CC 4403",
    driver: "Raj Patil",
    eta: "7:40 PM",
    action: ":",
  },
  {
    id: "#D1092",
    consignee: "Marathahalli",
    location: "Bangalore",
    status: "In Transit",
    vehicle: "KA 03 AA 5504",
    driver: "Sanjay Kumar",
    eta: "4:55 PM",
    action: ":",
  },
  {
    id: "#D1093",
    consignee: "Jayanagar",
    location: "Bangalore",
    status: "Delivered",
    vehicle: "KA 05 BB 6605",
    driver: "Ramesh Gowda",
    eta: "11:45 AM",
    action: ":",
  },
  {
    id: "#D1094",
    consignee: "Electronic City",
    location: "Bangalore",
    status: "Delayed",
    vehicle: "KA 51 CC 7706",
    driver: "Mahesh Naik",
    eta: "9:20 PM",
    action: ":",
  },
  {
    id: "#D1095",
    consignee: "Anna Nagar",
    location: "Chennai",
    status: "In Transit",
    vehicle: "TN 02 AA 8807",
    driver: "Bala Kumar",
    eta: "5:25 PM",
    action: ":",
  },
  {
    id: "#D1096",
    consignee: "Tambaram",
    location: "Chennai",
    status: "Pending",
    vehicle: "TN 11 BB 9908",
    driver: "Senthil Kumar",
    eta: "7:55 PM",
    action: ":",
  },
  {
    id: "#D1097",
    consignee: "Guindy",
    location: "Chennai",
    status: "Delivered",
    vehicle: "TN 09 CC 1109",
    driver: "Karthik Raj",
    eta: "1:20 PM",
    action: ":",
  },
  {
    id: "#D1098",
    consignee: "MI Road",
    location: "Jaipur",
    status: "In Transit",
    vehicle: "RJ 14 DD 2210",
    driver: "Ankur Sharma",
    eta: "4:05 PM",
    action: ":",
  },
  {
    id: "#D1099",
    consignee: "Mansarovar",
    location: "Jaipur",
    status: "Pending",
    vehicle: "RJ 14 EE 3311",
    driver: "Vivek Jain",
    eta: "6:25 PM",
    action: ":",
  },
  {
    id: "#D1100",
    consignee: "Jagatpura",
    location: "Jaipur",
    status: "Delivered",
    vehicle: "RJ 14 FF 4412",
    driver: "Sahil Gupta",
    eta: "12:15 PM",
    action: ":",
  },

  {
    id: "#D1101",
    consignee: "Sector 15",
    location: "Faridabad",
    status: "In Transit",
    vehicle: "HR 51 AA 5513",
    driver: "Kamal Kumar",
    eta: "5:35 PM",
    action: ":",
  },
  {
    id: "#D1102",
    consignee: "NIT",
    location: "Faridabad",
    status: "Delivered",
    vehicle: "HR 51 BB 6614",
    driver: "Dheeraj Singh",
    eta: "10:45 AM",
    action: ":",
  },
  {
    id: "#D1103",
    consignee: "Ballabhgarh",
    location: "Faridabad",
    status: "Pending",
    vehicle: "HR 51 CC 7715",
    driver: "Puneet Sharma",
    eta: "7:05 PM",
    action: ":",
  },
  {
    id: "#D1104",
    consignee: "Sector 14",
    location: "Sonipat",
    status: "In Transit",
    vehicle: "HR 10 AA 8816",
    driver: "Sahil Kumar",
    eta: "4:15 PM",
    action: ":",
  },
  {
    id: "#D1105",
    consignee: "Model Town",
    location: "Sonipat",
    status: "Delivered",
    vehicle: "HR 10 BB 9917",
    driver: "Ravi Malik",
    eta: "1:05 PM",
    action: ":",
  },
  {
    id: "#D1106",
    consignee: "Murthal",
    location: "Sonipat",
    status: "Delayed",
    vehicle: "HR 10 CC 1018",
    driver: "Ankit Dahiya",
    eta: "8:25 PM",
    action: ":",
  },
  {
    id: "#D1107",
    consignee: "Race Course",
    location: "Vadodara",
    status: "In Transit",
    vehicle: "GJ 06 DD 2119",
    driver: "Rohan Patel",
    eta: "5:10 PM",
    action: ":",
  },
  {
    id: "#D1108",
    consignee: "Karelibaug",
    location: "Vadodara",
    status: "Pending",
    vehicle: "GJ 06 EE 3220",
    driver: "Mitesh Shah",
    eta: "7:35 PM",
    action: ":",
  },
  {
    id: "#D1109",
    consignee: "Manjalpur",
    location: "Vadodara",
    status: "Delivered",
    vehicle: "GJ 06 FF 4321",
    driver: "Dhruv Patel",
    eta: "12:40 PM",
    action: ":",
  },
  {
    id: "#D1110",
    consignee: "C Scheme",
    location: "Jaipur",
    status: "In Transit",
    vehicle: "RJ 14 GG 5422",
    driver: "Ravi Sharma",
    eta: "3:25 PM",
    action: ":",
  },

  {
    id: "#D1111",
    consignee: "Shastri Nagar",
    location: "Jaipur",
    status: "Delivered",
    vehicle: "RJ 14 HH 6523",
    driver: "Manish Gupta",
    eta: "11:10 AM",
    action: ":",
  },
  {
    id: "#D1112",
    consignee: "Sodala",
    location: "Jaipur",
    status: "Pending",
    vehicle: "RJ 14 JJ 7624",
    driver: "Amit Saini",
    eta: "6:35 PM",
    action: ":",
  },
  {
    id: "#D1113",
    consignee: "Gariahat",
    location: "Kolkata",
    status: "In Transit",
    vehicle: "WB 04 AA 8725",
    driver: "Sourav Das",
    eta: "4:40 PM",
    action: ":",
  },
  {
    id: "#D1114",
    consignee: "Howrah",
    location: "Kolkata",
    status: "Delivered",
    vehicle: "WB 12 BB 9826",
    driver: "Arijit Roy",
    eta: "1:15 PM",
    action: ":",
  },
  {
    id: "#D1115",
    consignee: "New Town",
    location: "Kolkata",
    status: "Delayed",
    vehicle: "WB 08 CC 1027",
    driver: "Subhajit Paul",
    eta: "8:40 PM",
    action: ":",
  },
  {
    id: "#D1116",
    consignee: "Saibaba Colony",
    location: "Coimbatore",
    status: "In Transit",
    vehicle: "TN 37 AA 2128",
    driver: "Prakash Kumar",
    eta: "5:00 PM",
    action: ":",
  },
  {
    id: "#D1117",
    consignee: "RS Puram",
    location: "Coimbatore",
    status: "Delivered",
    vehicle: "TN 37 BB 3229",
    driver: "Hari Krishnan",
    eta: "12:25 PM",
    action: ":",
  },
  {
    id: "#D1118",
    consignee: "Peelamedu",
    location: "Coimbatore",
    status: "Pending",
    vehicle: "TN 37 CC 4330",
    driver: "Gokul Raj",
    eta: "7:10 PM",
    action: ":",
  },
  {
    id: "#D1119",
    consignee: "Kharadi",
    location: "Pune",
    status: "In Transit",
    vehicle: "MH 12 JJ 5431",
    driver: "Abhishek Patil",
    eta: "4:35 PM",
    action: ":",
  },
  {
    id: "#D1120",
    consignee: "Hadapsar",
    location: "Pune",
    status: "Delivered",
    vehicle: "MH 12 KK 6532",
    driver: "Sagar Shinde",
    eta: "1:35 PM",
    action: ":",
  },
];

export default allDelivery;
